### ISSUE TITLE
Question on implementing dropdowns

### ISSUE THREAD

**Issue by eddyystop** [philtoms/mithril-starter-kit#7]
An open dropdown should close when the user clicks anywhere on the page. I've implemented this elsewhere by giving each dropdown a sequential id# and maintaining a global-ish value containing the id# of the currently open dropdown.

This approach also requires a page-level parent whose onclick clears the currently open id#.

I don't like this approach for multiple reasons: onclick must propagate to the page-level parent, the page-level component is required, the dropdown component refers to an external view-model value.

Could you suggest any improvements? Thanks.

**Comment by philtoms** [comment]
Well I don't know about improvements ;) Assuming your id# is model rather than DOM, I think a page level click handler would be fine. Do you have something like this in mind?

``` javascript
(function(){
  var uiState = {
    itemId:0,
    ctrlId:0,
    isOpen: function(ctrlId,id){
      var isOpen = ctrlId === uiState.ctrlId && id === uiState.itemId
      return {style:'display:'+(isOpen? 'block':'none')}
    },
    clear:function(){
     uiState.ctrlId=0
     m.redraw()
    }
    // other state...
  }
  var registerId=0
  document.addEventListener('click', uiState.clear)

  m.element('dropdown', {
    controller: function(options){
      this.id = ++registerId
    },
    view: function(ctrl, inner){
      return m('.dropdown', [
        m('button', ....),
        inner.map(function(menu, id){
          m('.dropdown-menu', uiState.isOpen(ctrl.id,id), menu)
      })])
    }
  })
})()
```

Dropdown state is model driven, so a simple body level click handler - in the same scope as the dropdown (vm or module) - would have access to a shared state object / value. I would imagine that this state value would be compatible with all of the ui widgets defined in the same scope, each responding to state change in its own way. I think this is how I would progress with my little bootstrap wannabe.

**Comment by philtoms** [comment]
Of course I haven't actually tried this - I'm pretty certain that a more elaborate body click handler would be required for debounce.

**Comment by eddyystop** [comment]
Yes, I had used basically what you wrote. Since the component defn can add what it needs to something like uiState, then its docs need only mention the caveat that click events need to bubble up.
